### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory

### ISSUE THREAD

**Issue by MarcelGor** [jcustenborder/kafka-connect-transform-xml#43]
Hi,

i get this Exception any ideas what could be the problem?

thx
`
 [2021-10-19 08:07:53,320] ERROR Failed to start task mq-source_test_02-0 (org.apache.kafka.connect.runtime.Worker)
connect            | java.lang.AssertionError: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
connect            |  - with linked exception:
connect            | [java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
connect            |    at com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationContext(BindInfo.java:356)
connect            |    at com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationUnmarshaller(BindInfo.java:362)
connect            |    at com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl$1.<init>(AnnotationParserFactoryImpl.java:85)
connect            |    at com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl.create(AnnotationParserFactoryImpl.java:84)
connect            |    at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.createAnnotationParser(NGCCRuntimeEx.java:401)

`

**Comment by jcustenborder** [comment]
You need to copy more than just the `kafka-connect-transform-xml`. Run `mvn clean package` there should be a zip created with all of the contents needed. Please feel free to reopen if this doesn't resolve it.
